### ISSUE TITLE
Incompatible with latest create -f release.

### ISSUE THREAD

**Issue by solonovamax** [thexaero/opac-fabric-create-support#8]
The fix for this is to replace the import for `io.github.fabricators_of_create.porting_lib.util.FluidStack` with `io.github.fabricators_of_create.porting_lib.fluids.FluidStack`.

However, this class *only* exists for >= 1.19, and not for 1.18.2, so you'd need to split the sources between those two versions.

I was going to attempt to PR, however since it's not supported in 1.18, I'm not sure how you want to handle that, so I won't PR.

The temporary fix for this is to downgrade opac-fabric-create-support and opac to 1.3.0 and 0.20.4, respectively.

**Comment by thexaero** [comment]
Thanks for the info!
Seems to only affect 1.20.1, not 1.19.2 or older though.
I'll fix it ASAP.

**Comment by thexaero** [comment]
Simply going to have 2 variants of the extension now, one for 1.18-19 and one for 1.20+.

**Comment by solonovamax** [comment]
> Seems to only affect 1.20.1, not 1.19.2 or older though.

huh, I checked the 1.19.4 branch and it seemed to have that change. though, I didn't check the 1.19.2 one.
but maybe they didn't push it? dunno

**Comment by thexaero** [comment]
It's still in the old package on 1.19.4: https://github.com/Fabricators-of-Create/Porting-Lib/blob/1.19.4/transfer/src/main/java/io/github/fabricators_of_create/porting_lib/util/FluidStack.java
